# Generated by Django 3.2 on 2021-04-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
