# Generated by Django 3.2 on 2021-04-12 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='card_number',
            field=models.CharField(editable=False, max_length=16, validators=[django.core.validators.RegexValidator(message='Wrong card number', regex='[0-9]{16}')]),
        ),
    ]
