# Generated by Django 3.2 on 2021-04-12 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20210412_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='card_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Wrong card number', regex='[0-9]{16}')]),
        ),
    ]
